[project]
name = "call-me-maybe"
version = "0.1.0"
description = "A python implementation of function calling with constrained decoding and an LLM"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
	"llm-sdk==0.0.10",
	"pydantic==2.10.4",
	"torchvision>=0.15.0",
	"torch",
	"accelerate",
	"mypy>=2.1.0",
]

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/rocm7.2"

[tool.uv.sources]
llm-sdk = { path = "llm_sdk", editable = true }
